### ISSUE TITLE
Why Piracy Support?

### ISSUE THREAD

**Issue by ilyaigpetrov** [brightflash64/MOFO-Linux#1]
Popcorn Time is mainly used for watching pirated videos. Some countries may put films under censorship ban and Popcorn Time may be a solution but there is also Netflix or other legal alternatives you may provide access to.

Why do you really need to include it in the distro?

This issue is not a quibble, but rather a request for comment for my better understanding of Popcorn Time importance in context of censorship.

Looking forward to your clarification,
Ilya.

**Comment by ilyaigpetrov** [comment]
Ok, @brightflash64, I think I got it.

Strong censorship in totalitarian countries cuts people away from good free films on free national channels and they have issues with buying it because of low salaries in economics controlled by the government.
They are downplayed by their government already, so why to push them to pay last pennies for better life quality they were deprived of.

Cheers,
Ilya.

**Comment by brightflash64** [comment]
Hi,
The main issue was not price.  It was having a capability to get content beyond the control of the censors.  MOFO Linux version 5 includes means to get audio and video content without censorship, but without the ethical or legal risks of Popcorn-Time.
Cheers,MOFO Linux 

    On Tuesday, November 15, 2016 7:44 AM, Ilya Ig. Petrov <notifications@github.com> wrote:
 

 Ok, @brightflash64, I think I got it.Strong censorship in totalitarian countries cuts people away from good free films on free national channels and they have issues with buying it because of low salaries in economics controlled by the government.
They are downplayed by their government already, so why to push them to pay last pennies for better life quality they were deprived of.Cheers,
Ilya.—
